"""
comfyui-gpt-image
Generate an image by calling gpt-image-1 API
"""

from .nodes_api import (
    NODE_CLASS_MAPPINGS as API_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as API_NODE_DISPLAY_NAME_MAPPINGS,
)
from .wizard import (
    NODE_CLASS_MAPPINGS as WIZARD_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as WIZARD_NODE_DISPLAY_NAME_MAPPINGS,
)
from .chat_node import (
    NODE_CLASS_MAPPINGS as CHAT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CHAT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .server import *

# Merge node mappings from the API nodes and the wizard node.
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(API_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(WIZARD_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CHAT_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(API_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(WIZARD_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(CHAT_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = './web'

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']